# -*- coding: utf-8 -*-
"""Template_Submission_Akhir.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2x3UqGro7t4bkahHZjLXMd-80250q02

# Proyek Klasifikasi Gambar: Animals-10 (Top-5 Dinamis)
- **Nama:** Ahmad Meijlan Yasir
- **Email:** yasirahmad220504@gmail.com
- **ID Dicoding:** Ahmad Meijlan Yasir

## Import Semua Packages/Library yang Digunakan

### Imports & Setup (Environment)
"""

import glob
import json
import math
import random
import shutil
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image, UnidentifiedImageError

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.metrics import classification_report, confusion_matrix

from IPython.display import display

# KaggleHub (dipakai untuk download dataset)
import kagglehub

# Google Colab Drive
try:
    from google.colab import drive  # type: ignore
except Exception:
    drive = None

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)


def ensure_pip_package(pkg: str) -> None:
    """Pastikan paket tersedia pada environment yang sedang dipakai notebook."""
    try:
        __import__(pkg)
    except ModuleNotFoundError:
        print(f"[INFO] Installing missing package: {pkg}")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])
        __import__(pkg)


# Pastikan tensorflowjs tersedia sebelum proses konversi TFJS
ensure_pip_package("tensorflowjs")
import tensorflowjs as tfjs

"""### Paths & Project Structure"""

# Mount Google Drive (hanya jika run di Colab)
if drive is not None:
    try:
        drive.mount('/content/drive')
    except Exception as e:
        print("[INFO] drive.mount gagal:", repr(e))
else:
    print("[INFO] google.colab.drive tidak tersedia (bukan Colab).")

# ===== Root Directories (Best practice Colab) =====
# 1) Runtime (cepat, sementara) untuk komputasi + banyak I/O
RUNTIME_DIR = Path("/content/cc26_runtime")

# 2) Drive (persisten) hanya untuk artefak submission
DRIVE_DIR = Path("/content/drive/MyDrive")
PROJECT_DIR_DRIVE = DRIVE_DIR / "CC26 - Image Classification"

# ===== Working dirs (runtime) =====
DATASETS_DIR = RUNTIME_DIR / "datasets"
RAW_IT_DIR = DATASETS_DIR / "animals10_raw_it"   # copy rapi (Italia)
RAW_EN_DIR = DATASETS_DIR / "animals10_raw_en"   # hasil rename (English)

WORK_DIR = RUNTIME_DIR / "work_top5"
SPLIT_DIR = RUNTIME_DIR / "splits"
CACHE_DIR = RUNTIME_DIR / "cache"
ARTIFACTS_DIR = RUNTIME_DIR / "artifacts"

# ===== Submission dir (Drive) =====
SUBMISSION_DIR = PROJECT_DIR_DRIVE / "submission"


def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


for p in [RUNTIME_DIR, DATASETS_DIR, WORK_DIR, SPLIT_DIR, CACHE_DIR, ARTIFACTS_DIR, PROJECT_DIR_DRIVE, SUBMISSION_DIR]:
    ensure_dir(p)

print("RUNTIME_DIR:", RUNTIME_DIR)
print("PROJECT_DIR_DRIVE:", PROJECT_DIR_DRIVE)
print("SUBMISSION_DIR:", SUBMISSION_DIR)

DATASET_ROOT: Path | None = None

"""### Utils (Reusable Functions)"""

def iter_image_files(class_dir: Path):
    exts = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp"}
    for p in class_dir.rglob("*"):
        if p.is_file() and p.suffix.lower() in exts:
            yield p


def count_images_per_class(dataset_dir: Path) -> pd.DataFrame:
    rows = []
    for class_dir in sorted([d for d in dataset_dir.iterdir() if d.is_dir()]):
        n = sum(1 for _ in iter_image_files(class_dir))
        rows.append({"class": class_dir.name, "n_images": n})
    df = pd.DataFrame(rows).sort_values("n_images", ascending=False).reset_index(drop=True)
    df["pct"] = (df["n_images"] / df["n_images"].sum() * 100).round(2)
    return df


def show_sample_images(dataset_dir: Path, class_names: list[str], n_per_class: int = 3, figsize=(12, 10)):
    rng = random.Random(SEED)
    fig, axes = plt.subplots(len(class_names), n_per_class, figsize=figsize)
    for i, cls in enumerate(class_names):
        files = list(iter_image_files(dataset_dir / cls))
        picks = rng.sample(files, k=min(n_per_class, len(files)))
        for j in range(n_per_class):
            ax = axes[i, j] if len(class_names) > 1 else axes[j]
            ax.axis("off")
            if j < len(picks):
                img = Image.open(picks[j]).convert("RGB")
                ax.imshow(img)
                if j == 0:
                    ax.set_title(cls)
    plt.tight_layout()
    plt.show()


def print_images_resolution(directory: Path, max_images_per_class: int | None = 200):

    unique_sizes = set()
    total_images = 0

    for subdir in sorted([d for d in directory.iterdir() if d.is_dir()]):
        image_files = list(iter_image_files(subdir))
        num_images = len(image_files)
        print(f"{subdir.name}: {num_images}")
        total_images += num_images

        files_to_scan = image_files if max_images_per_class is None else image_files[:max_images_per_class]
        for img_path in files_to_scan:
            try:
                with Image.open(img_path) as img:
                    unique_sizes.add(img.size)
            except (UnidentifiedImageError, OSError, ValueError):
                continue

    print("\nJumlah resolusi unik:", len(unique_sizes))
    for size in list(sorted(unique_sizes))[:15]:
        print(f"- {size}")

    print(f"\nTotal gambar (semua kelas): {total_images}")


@dataclass
class AuditResult:
    total_files: int
    corrupt_files: list
    sampled: int
    unique_resolutions: int
    resolution_examples: list


def audit_dataset_resolution_and_corrupt(dataset_dir: Path, sample_size: int = 400) -> AuditResult:
    all_files = []
    for class_dir in [d for d in dataset_dir.iterdir() if d.is_dir()]:
        all_files.extend(list(iter_image_files(class_dir)))

    if not all_files:
        return AuditResult(total_files=0, corrupt_files=[], sampled=0, unique_resolutions=0, resolution_examples=[])

    sample = random.sample(all_files, k=min(sample_size, len(all_files)))

    corrupt = []
    resolutions = []

    for p in sample:
        try:
            with Image.open(p) as im:
                im.verify()
            with Image.open(p) as im:
                resolutions.append(im.size)  # (width, height)
        except (UnidentifiedImageError, OSError, ValueError):
            corrupt.append(p)

    counter = Counter(resolutions)
    examples = counter.most_common(10)

    return AuditResult(
        total_files=len(all_files),
        corrupt_files=corrupt,
        sampled=len(sample),
        unique_resolutions=len(counter),
        resolution_examples=examples,
    )


def delete_files(files: list[Path]) -> int:
    deleted = 0
    for p in files:
        try:
            p.unlink(missing_ok=True)
            deleted += 1
        except OSError:
            pass
    return deleted


def copy_class_subset(src_dataset_dir: Path, dst_dataset_dir: Path, class_names: list[str]) -> None:
    ensure_dir(dst_dataset_dir)
    for cls in class_names:
        src = src_dataset_dir / cls
        dst = dst_dataset_dir / cls
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)

"""## Data Preparation — Download & Setup Dataset (KaggleHub → Colab)

Bagian ini:
- Download dataset dari KaggleHub.
- Menyalin dataset ke folder kerja yang rapi.
- Mengubah nama kelas (Italia → English) pada seluruh `raw-img`.
- Menetapkan `DATASET_ROOT` untuk eksplorasi dan proses berikutnya.

### Download dataset (KaggleHub)
"""

kaggle_cache_path = Path(kagglehub.dataset_download("alessiocorrado99/animals10"))
print("KaggleHub cache path:", kaggle_cache_path)

"""### Deteksi struktur dataset (raw-img + translate.py)"""

def find_animals10_root(p: Path) -> Path:
    if (p / "raw-img").exists():
        return p

    for cand in p.rglob("raw-img"):
        if cand.is_dir():
            return cand.parent

    raise RuntimeError("Tidak menemukan folder 'raw-img' pada hasil download KaggleHub.")


src_root_it = find_animals10_root(kaggle_cache_path)
src_raw_img_it = src_root_it / "raw-img"
src_translate = src_root_it / "translate.py"

print("src_root_it:", src_root_it)
print("src_raw_img_it:", src_raw_img_it, "| exists:", src_raw_img_it.exists())
print("src_translate:", src_translate, "| exists:", src_translate.exists())

"""### Salin dataset ke folder raw (Italia) yang rapi"""

def copy_tree_clean(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


copy_tree_clean(src_raw_img_it, RAW_IT_DIR / "raw-img")

if src_translate.exists():
    ensure_dir(RAW_IT_DIR)
    shutil.copy2(src_translate, RAW_IT_DIR / "translate.py")

print("RAW_IT_DIR:", RAW_IT_DIR)
print("Kelas terdeteksi (Italia):", sorted([d.name for d in (RAW_IT_DIR / "raw-img").iterdir() if d.is_dir()]))

"""### Mapping kelas Italia → English"""

IT_TO_EN = {
    "cane": "dog",
    "cavallo": "horse",
    "elefante": "elephant",
    "farfalla": "butterfly",
    "gallina": "chicken",
    "gatto": "cat",
    "mucca": "cow",
    "pecora": "sheep",
    "ragno": "spider",
    "scoiattolo": "squirrel",
}

print("Mapping Italia→English siap")

"""### Buat raw-img versi English"""

raw_it = RAW_IT_DIR / "raw-img"
raw_en = RAW_EN_DIR / "raw-img"

if RAW_EN_DIR.exists():
    shutil.rmtree(RAW_EN_DIR)
ensure_dir(raw_en)

missing = [c for c in IT_TO_EN.keys() if not (raw_it / c).exists()]
if missing:
    raise RuntimeError(f"Kelas Italia berikut tidak ditemukan: {missing}")

for it_name, en_name in IT_TO_EN.items():
    shutil.copytree(raw_it / it_name, raw_en / en_name)

# copy translate.py agar terdokumentasi
translate_local = RAW_IT_DIR / "translate.py"
if translate_local.exists():
    shutil.copy2(translate_local, RAW_EN_DIR / "translate.py")

print("RAW_EN_DIR:", RAW_EN_DIR)
print("Kelas terdeteksi (English):", sorted([d.name for d in raw_en.iterdir() if d.is_dir()]))

"""### Set `DATASET_ROOT` untuk eksplorasi (English)"""

DATASET_ROOT = RAW_EN_DIR / "raw-img"
print("DATASET_ROOT:", DATASET_ROOT)

"""## Eksplorasi Dataset & Subset Top-5

Bagian ini memuat:
- Load dataset lengkap (10 kelas) untuk eksplorasi.
- Keputusan memilih Top-5 kelas (dinamis).
- Menyiapkan dataset kerja Top-5

### Load Dataset (Full - 10 Kelas)
"""

if DATASET_ROOT is None or (not DATASET_ROOT.exists()):
    raise RuntimeError(f"DATASET_ROOT tidak valid: {DATASET_ROOT}")

all_classes = sorted([d.name for d in DATASET_ROOT.iterdir() if d.is_dir()])
print("Jumlah kelas terdeteksi:", len(all_classes))
print("Nama kelas:", all_classes)

src_root = DATASET_ROOT
print("Folder dataset sumber:", src_root)

"""### Eksplorasi: Jumlah gambar per kelas (Full - 10 Kelas)"""

df_counts_full = count_images_per_class(src_root)
display(df_counts_full)
print("Total gambar (10 kelas):", int(df_counts_full["n_images"].sum()))

"""### Eksplorasi: Sebaran label (Full - 10 Kelas)"""

plt.figure(figsize=(10, 4))
plt.bar(df_counts_full["class"], df_counts_full["n_images"])
plt.title("Distribusi jumlah gambar per kelas (10 kelas)")
plt.xlabel("Kelas")
plt.ylabel("Jumlah gambar")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""### Eksplorasi: Variasi resolusi gambar (bukti resolusi tidak seragam)"""

print_images_resolution(src_root, max_images_per_class=200)

"""### Keputusan: Ambil Top-5 kelas dengan jumlah gambar terbanyak (dinamis)"""

TOP5_CLASSES = df_counts_full.sort_values("n_images", ascending=False).head(5)["class"].tolist()
print("Top-5 kelas (dinamis):", TOP5_CLASSES)

df_top5 = df_counts_full[df_counts_full["class"].isin(TOP5_CLASSES)].reset_index(drop=True)
display(df_top5)
print("Total gambar Top-5:", int(df_top5["n_images"].sum()))

"""### Siapkan dataset kerja (Top-5)

Langkah pada bagian ini dipisah per cell agar mudah dibaca.
"""

if WORK_DIR.exists():
    shutil.rmtree(WORK_DIR)
ensure_dir(WORK_DIR)

print("WORK_DIR:", WORK_DIR)

"""#### Copy subset Top-5 ke dataset kerja"""

copy_class_subset(src_root, WORK_DIR, TOP5_CLASSES)
print("Subset Top-5 disalin ke WORK_DIR")

"""#### Contoh gambar (Top-5)"""

show_sample_images(WORK_DIR, TOP5_CLASSES, n_per_class=3)

"""#### Audit Top-5 (jumlah gambar + bukti resolusi tidak seragam)"""

subset_counts = count_images_per_class(WORK_DIR)
display(subset_counts)
print("Total gambar Top-5 (WORK_DIR):", int(subset_counts["n_images"].sum()))

audit = audit_dataset_resolution_and_corrupt(WORK_DIR, sample_size=500)
print("Jumlah file subset:", audit.total_files)
print("Jumlah sample untuk audit resolusi:", audit.sampled)
print("Jumlah resolusi unik (bukti resolusi tidak seragam):", audit.unique_resolutions)
print("Contoh resolusi (top 10):")
for (w_h, n) in audit.resolution_examples:
    print(f"- {w_h}: {n} file")

"""#### Cleaning file corrupt dan pengecekan ulang"""

print("File corrupt terdeteksi (dari sample):", len(audit.corrupt_files))
if audit.corrupt_files:
    deleted = delete_files(audit.corrupt_files)
    print("File corrupt dihapus:", deleted)

subset_counts_after = count_images_per_class(WORK_DIR)
display(subset_counts_after)
print("Total gambar Top-5 setelah cleaning:", int(subset_counts_after["n_images"].sum()))

"""### Data Preprocessing

#### Split Dataset
"""

# Helper split stratified 70/15/15

def reset_dir(p: Path) -> None:
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)


def list_class_files(dataset_dir: Path, class_name: str) -> list[Path]:
    return sorted(list(iter_image_files(dataset_dir / class_name)))


def split_paths(paths: list[Path], train_ratio=0.7, val_ratio=0.15):
    assert 0 < train_ratio < 1
    assert 0 < val_ratio < 1
    rng = random.Random(SEED)
    paths = list(paths)
    rng.shuffle(paths)

    n = len(paths)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)

    train_paths = paths[:n_train]
    val_paths = paths[n_train:n_train + n_val]
    test_paths = paths[n_train + n_val:]
    return train_paths, val_paths, test_paths


def copy_split(split_name: str, class_name: str, paths: list[Path]) -> None:
    dst = SPLIT_DIR / split_name / class_name
    ensure_dir(dst)
    for p in paths:
        shutil.copy2(p, dst / p.name)

"""#### Eksekusi split (train/val/test)"""

reset_dir(SPLIT_DIR)

split_summary = []
all_seen = set()

for cls in TOP5_CLASSES:
    files = list_class_files(WORK_DIR, cls)
    train_p, val_p, test_p = split_paths(files, train_ratio=0.7, val_ratio=0.15)

    for subset, subset_paths in [("train", train_p), ("val", val_p), ("test", test_p)]:
        for p in subset_paths:
            key = (p.name, cls)
            if key in all_seen:
                raise RuntimeError(f"Data leakage terdeteksi untuk file: {p}")
            all_seen.add(key)

    copy_split("train", cls, train_p)
    copy_split("val", cls, val_p)
    copy_split("test", cls, test_p)

    split_summary.append(
        {"class": cls, "n_train": len(train_p), "n_val": len(val_p), "n_test": len(test_p), "n_total": len(files)}
    )

split_df = pd.DataFrame(split_summary)
display(split_df)

"""#### Ringkasan dan verifikasi split"""

print("Total train:", int(split_df["n_train"].sum()))
print("Total val:", int(split_df["n_val"].sum()))
print("Total test:", int(split_df["n_test"].sum()))

for split_name in ["train", "val", "test"]:
    classes_in_split = sorted([d.name for d in (SPLIT_DIR / split_name).iterdir() if d.is_dir()])
    print(split_name, "->", classes_in_split)

"""## Data Loading

Memuat dataset hasil split (train/val/test) dari folder `SPLIT_DIR`.
"""

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    SPLIT_DIR / "train",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
)
val_ds = tf.keras.utils.image_dataset_from_directory(
    SPLIT_DIR / "val",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
)
test_ds = tf.keras.utils.image_dataset_from_directory(
    SPLIT_DIR / "test",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False,
)

class_names = train_ds.class_names
print("class_names:", class_names)
print("Jumlah kelas (Top-5):", len(class_names))

"""## Data Preprocessing

Normalisasi dan augmentasi (augmentasi hanya untuk data training).
"""

normalization_layer = layers.Rescaling(1.0 / 127.5, offset=-1)

data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal", seed=SEED),
        layers.RandomRotation(0.05, seed=SEED),
        layers.RandomZoom(0.1, seed=SEED),
        layers.RandomContrast(0.1, seed=SEED),
    ],
    name="data_augmentation",
)

def prepare_for_training(ds: tf.data.Dataset, training: bool, cache_name: str):
    if training:
        ds = ds.map(
            lambda x, y: (data_augmentation(x, training=True), y),
            num_parallel_calls=tf.data.AUTOTUNE,
        )
    ds = ds.map(lambda x, y: (normalization_layer(x), y), num_parallel_calls=tf.data.AUTOTUNE)

    cache_path = (CACHE_DIR / cache_name).as_posix()
    return ds.cache(cache_path).prefetch(tf.data.AUTOTUNE)


train_ds_prep = prepare_for_training(train_ds, training=True, cache_name="train")
val_ds_prep = prepare_for_training(val_ds, training=False, cache_name="val")
test_ds_prep = prepare_for_training(test_ds, training=False, cache_name="test")

for images, labels in train_ds_prep.take(1):
    print("Batch images:", images.shape, images.dtype)
    print("Batch labels:", labels.shape, labels.dtype)

"""## Modelling

Membangun dan melatih model CNN (Sequential + Conv2D + MaxPooling2D) dengan callback.
"""

# Model CNN Sequential + Transfer Learning (MobileNetV2) dengan Sequential + Conv2D + Pooling Layer

num_classes = len(class_names)

base_model = keras.applications.MobileNetV2(
    input_shape=IMG_SIZE + (3,),
    include_top=False,
    weights="imagenet",
)
base_model.trainable = False

model = keras.Sequential(
    [
        layers.Input(shape=IMG_SIZE + (3,)),
        base_model,
        layers.Conv2D(128, (3, 3), activation="relu", padding="same"),
        layers.MaxPooling2D(),
        layers.GlobalAveragePooling2D(),
        layers.Dropout(0.3),
        layers.Dense(256, activation="relu"),
        layers.Dropout(0.3),
        layers.Dense(num_classes, activation="softmax"),
    ],
    name="cnn_animals10_top5_mobilenetv2",
)

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=keras.losses.SparseCategoricalCrossentropy(),
    metrics=["accuracy"],
)

model.summary()

"""### Callback"""

ckpt_dir = ARTIFACTS_DIR / "checkpoints"
ensure_dir(ckpt_dir)
ckpt_path = ckpt_dir / "best_model.keras"

callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=5, restore_best_weights=True),
    keras.callbacks.ModelCheckpoint(ckpt_path.as_posix(), monitor="val_accuracy", save_best_only=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2),
]

"""### Training"""

EPOCHS = 30
history = model.fit(
    train_ds_prep,
    validation_data=val_ds_prep,
    epochs=EPOCHS,
    callbacks=callbacks,
)

"""### Load model terbaik (checkpoint)"""

if ckpt_path.exists():
    print("Checkpoint Keras tersimpan di:", ckpt_path)
    print("(Inference akan memakai SavedModel.)")

"""## Evaluasi dan Visualisasi

Menunjukkan performa model pada train/validation/test serta visualisasi metrik dan analisis kesalahan.

### Evaluasi train/validation/test
"""

# Evaluasi metrik lengkap untuk Train / Val / Test

def eval_split(ds, name: str):
    loss, acc = model.evaluate(ds, verbose=0)
    return {"split": name, "loss": float(loss), "accuracy": float(acc)}

metrics_rows = [
    eval_split(train_ds_prep, "train"),
    eval_split(val_ds_prep, "val"),
    eval_split(test_ds_prep, "test"),
]
metrics_df = pd.DataFrame(metrics_rows)
display(metrics_df.style.format({"loss": "{:.4f}", "accuracy": "{:.4f}"}))

print("\nRingkas:\n")
for r in metrics_rows:
    print(f"- {r['split']:<5} | loss: {r['loss']:.4f} | acc: {r['accuracy']:.4f}")

"""### Plot accuracy dan loss"""

acc = history.history.get("accuracy", [])
val_acc_hist = history.history.get("val_accuracy", [])
loss = history.history.get("loss", [])
val_loss_hist = history.history.get("val_loss", [])

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(acc, label="train_acc")
plt.plot(val_acc_hist, label="val_acc")
plt.title("Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(loss, label="train_loss")
plt.plot(val_loss_hist, label="val_loss")
plt.title("Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.tight_layout()
plt.show()

"""### Confusion matrix (test set)"""

y_true = []
y_pred = []

def predict_batches_for_metrics(ds):
    for batch_x, batch_y in ds:
        probs = model.predict(batch_x, verbose=0)
        preds = np.argmax(probs, axis=1)
        yield batch_y.numpy(), preds

for y_b, p_b in predict_batches_for_metrics(test_ds_prep):
    y_true.extend(y_b.tolist())
    y_pred.extend(p_b.tolist())

y_true = np.array(y_true)
y_pred = np.array(y_pred)

cm = confusion_matrix(y_true, y_pred)
print("Confusion Matrix (Test):")
print(cm)

plt.figure(figsize=(7, 6))
plt.imshow(cm, interpolation="nearest")
plt.title("Confusion Matrix (Test)")
plt.colorbar()

tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names, rotation=45, ha="right")
plt.yticks(tick_marks, class_names)

thresh = cm.max() / 2.0
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(
            j,
            i,
            format(cm[i, j], "d"),
            ha="center",
            va="center",
            color="white" if cm[i, j] > thresh else "black",
        )

plt.ylabel("True label")
plt.xlabel("Predicted label")
plt.tight_layout()
plt.show()

"""### Classification report (test set)"""

print(classification_report(y_true, y_pred, target_names=class_names))

"""### Contoh prediksi (beberapa gambar dari test set)"""

def show_predictions(ds, n=12):
    images, labels = next(iter(ds.take(1)))
    probs = model.predict(images, verbose=0)
    preds = np.argmax(probs, axis=1)

    n = min(n, images.shape[0])
    plt.figure(figsize=(14, 10))
    for i in range(n):
        ax = plt.subplot(3, 4, i + 1)
        plt.imshow(images[i].numpy())
        true_name = class_names[int(labels[i])]
        pred_name = class_names[int(preds[i])]
        conf = float(np.max(probs[i]))
        title = f"True: {true_name}\nPred: {pred_name} ({conf:.2f})"
        ax.set_title(title, fontsize=10)
        plt.axis("off")
    plt.tight_layout()
    plt.show()

show_predictions(test_ds, n=12)

"""## Konversi Model

Menyimpan model ke format **SavedModel**, **TF-Lite**, dan **TFJS** (sesuai kriteria submission).
"""

saved_model_dir = SUBMISSION_DIR / "saved_model"
tflite_dir = SUBMISSION_DIR / "tflite"
tfjs_dir = SUBMISSION_DIR / "tfjs_model"

for d in [saved_model_dir, tflite_dir, tfjs_dir]:
    ensure_dir(d)

print("Folder output konversi:", SUBMISSION_DIR)

"""### Simpan SavedModel"""

try:
    model.export(saved_model_dir.as_posix())
except Exception:
    model.save(saved_model_dir.as_posix())

print("SavedModel tersimpan di:", saved_model_dir)

"""### Konversi ke TF-Lite + `label.txt`"""

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir.as_posix())
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()

tflite_path = tflite_dir / "model.tflite"
tflite_path.write_bytes(tflite_model)
print("TFLite tersimpan di:", tflite_path)

label_path = tflite_dir / "label.txt"
label_path.write_text("\n".join(class_names), encoding="utf-8")
print("Label tersimpan di:", label_path)

"""### Konversi ke TFJS"""

tfjs.converters.save_keras_model(model, tfjs_dir.as_posix())
print("TFJS model tersimpan di:", tfjs_dir)

"""## Inference
Melakukan prediksi pada 3–5 gambar dan menampilkan bukti (gambar, label prediksi, confidence).
"""

# Ambil beberapa path file dari folder test untuk inference

test_paths = []
for cls in TOP5_CLASSES:
    cls_dir = SPLIT_DIR / "test" / cls
    test_paths.extend(sorted(list(iter_image_files(cls_dir))))

rng = random.Random(SEED)
selected_paths = rng.sample(test_paths, k=min(5, len(test_paths)))
print("Jumlah sample inference:", len(selected_paths))

"""### Preprocessing 1 gambar untuk inference"""

def load_and_preprocess_image(path: Path):
    img = Image.open(path).convert("RGB")
    img_resized = img.resize(IMG_SIZE)
    arr = (np.array(img_resized).astype(np.float32) / 127.5) - 1.0
    return img, np.expand_dims(arr, axis=0)

"""### Hasil inference (bukti)"""

loaded_sm = tf.saved_model.load(saved_model_dir.as_posix())
infer_sm = loaded_sm.signatures["serving_default"]

input_key = list(infer_sm.structured_input_signature[1].keys())[0]
output_key = list(infer_sm.structured_outputs.keys())[0]


def savedmodel_predict_proba(x_np: np.ndarray) -> np.ndarray:
    x_tf = tf.convert_to_tensor(x_np, dtype=tf.float32)
    out = infer_sm(**{input_key: x_tf})
    y = out[output_key].numpy()
    return y


plt.figure(figsize=(14, 6))
for i, p in enumerate(selected_paths):
    orig_img, x = load_and_preprocess_image(p)
    probs = savedmodel_predict_proba(x)[0]
    pred_idx = int(np.argmax(probs))
    pred_label = class_names[pred_idx]
    conf = float(np.max(probs))

    true_label = p.parent.name

    ax = plt.subplot(1, len(selected_paths), i + 1)
    plt.imshow(orig_img)
    plt.axis("off")
    ax.set_title(f"True: {true_label}\nPred: {pred_label}\nConf: {conf:.2f}", fontsize=10)

plt.tight_layout()
plt.show()

# Inference batch dari 10 gambar eksternal (URL)

TOP_K = 5

IMAGE_URLS = [
    # DOG
    "https://www.akc.org/wp-content/uploads/2017/11/Akita-standing-outdoors-in-the-summer.jpg",
    "https://hips.hearstapps.com/hmg-prod/images/golden-retriever-puppy-lying-down-on-grass-royalty-free-image-1766098805.pjpeg?crop=1.00xw:0.754xh;0,0.136xh",

    # HORSE
    "https://images.stockcake.com/public/0/c/f/0cfe09d2-8b24-40ea-97a1-45ac9a60f16a_large/majestic-horse-running-stockcake.jpg",
    "https://lh7-us.googleusercontent.com/f-zhn1fVem_NoW9ELOGQ21EZeHbdNLfKw3tfFblttScX3olF8qtHU-Xmc9JfAqueBmd-8c7DBXjwXJ4sRM8VJ1ZEBqXT7dQ-UztmVkWrDaOIfWSFzkua19JGC443paSjvYud9-tmv4_V-72GRA88TIY",

    # CHICKEN
    "https://cdn.britannica.com/18/137318-050-29F7072E/rooster-Rhode-Island-Red-roosters-chicken-domestication.jpg",
    "https://img.hobbyfarms.com/how-a-chickens-body-works-scaled.jpeg",

    # BUTTERFLY
    "https://www.popsci.com/wp-content/uploads/2023/05/15/ButterflyFamilyTree.png?quality=85&w=1536",
    "https://cdn.britannica.com/76/151376-050-13586FE2/monarch-butterfly-flowers-bush.jpg",

    # SPIDER
    "https://www.dupageforest.org/hubfs/Plants-Wildlife/Photos/Wildlife/Insects-Spiders-Crayfish/Spiders-Harvestmen-Ticks/Wolf-spider-c-Ziva-Amir-flickr.jpg",
    "https://extension.umd.edu/sites/extension.umd.edu/files/styles/optimized/public/2021-03/HGIC_spiders_wolfspider_16x9.jpg?itok=67vCkBvS",
]

external_dir = ARTIFACTS_DIR / "external_images"
ensure_dir(external_dir)

results = []

for idx, image_url in enumerate(IMAGE_URLS, start=1):
    try:
        downloaded_path = tf.keras.utils.get_file(
            fname=f"external_infer_image_{idx}.jpg",
            origin=image_url,
            cache_dir=external_dir.as_posix(),
        )

        img = Image.open(downloaded_path).convert("RGB")
        img_resized = img.resize(IMG_SIZE)
        arr = (np.array(img_resized).astype(np.float32) / 127.5) - 1.0
        x = np.expand_dims(arr, axis=0)

        # Predict via SavedModel
        probs = savedmodel_predict_proba(x)[0]
        top_idx = np.argsort(probs)[::-1][:TOP_K]
        pred_idx = int(top_idx[0])
        pred_name = class_names[pred_idx] if 'class_names' in globals() else str(pred_idx)
        pred_conf = float(probs[pred_idx])

        results.append({
            "url": image_url,
            "img": img,
            "status": "ok",
            "pred_name": pred_name,
            "pred_conf": pred_conf,
            "top_idx": top_idx,
            "probs": probs,
        })

    except Exception as e:
        results.append({
            "url": image_url,
            "img": None,
            "status": f"error: {e}",
            "pred_name": None,
            "pred_conf": None,
            "top_idx": None,
            "probs": None,
        })

# Tampilkan grid hasil
n = len(results)
cols = 2
rows = math.ceil(n / cols)

plt.figure(figsize=(12, 5 * rows))
for i, res in enumerate(results, start=1):
    ax = plt.subplot(rows, cols, i)
    if res["img"] is not None:
        plt.imshow(res["img"])
        title = f"Pred: {res['pred_name']} ({res['pred_conf']:.2f})"
    else:
        blank = np.ones((300, 300, 3), dtype=np.uint8) * 240
        plt.imshow(blank)
        title = "DOWNLOAD / INFERENCE FAILED"
    plt.axis("off")
    ax.set_title(title, fontsize=11)

plt.tight_layout()
plt.show()

# Detail top-k prediction
for i, res in enumerate(results, start=1):
    print("=" * 90)
    print(f"[{i}] URL: {res['url']}")
    print(f"Status: {res['status']}")

    if res["status"] == "ok":
        print(f"Prediksi utama: {res['pred_name']} ({res['pred_conf']:.4f})")
        print("Top predictions:")
        for j in res["top_idx"]:
            name = class_names[int(j)] if 'class_names' in globals() else str(j)
            print(f"- {name}: {res['probs'][j]:.4f}")